# Takes average values of stats calculated by r_playerstats.R for each cluster.
#
# Utilizes the []
#
# Created By: Nicholas Marina
# Created On: 6/20/19
# Last Updated: 6/20/19

library(dplyr)
library(stringr)

# The csv file generated by r_playerstats.R is read in.
playerstats <- read.csv(file='data/player_stats.csv')

# A vector is used to store each unique cluster index.
cluster <- unique(playerstats$cluster)

# Lists are initialized to store the statistics for each cluster.
kd <- list(avg=0, std=0, skew=0, slope=0, slope_std=0, prefix='kd_')
low <- list(avg=0, std=0, skew=0, slope=0, slope_std=0, prefix='low_')
mid <- list(avg=0, std=0, skew=0, slope=0, slope_std=0, prefix='mid_')
high <- list(avg=0, std=0, skew=0, slope=0, slope_std=0, prefix='high_')
stats <- list(kd, low, mid, high)

# Averages for each cluster are calculated and stored in the lists iteratively.
for(i in cluster){
	clusterstats <- filter(playerstats, cluster == i)
	for(j in 1:4){
		pref <- stats[[j]]$prefix
		avg_list <- clusterstats[,paste(pref, 'avg', sep='')]
		std_list <- clusterstats[,paste(pref, 'std', sep='')]
		skew_list <- clusterstats[,paste(pref, 'skew', sep='')]
		slope_list <- clusterstats[,paste(pref, 'slope', sep='')]
		slope_std_list <- clusterstats[,paste(pref, 'slope_std', sep='')]
		stats[[j]]$avg[i] <- mean(avg_list)
		stats[[j]]$std[i] <- mean(std_list)
		stats[[j]]$skew[i] <- mean(skew_list)
		stats[[j]]$slope[i] <- mean(slope_list)
		stats[[j]]$slope_std[i] <- mean(slope_std_list)
	}
}

# Stats are then placed in a dataframe.
clust_stats <- data.frame(cluster)
for(i in 1:4){
	pref <- stats[[i]]$prefix
	clust_stats[,paste(pref, 'avg', sep='')] <- stats[[i]]$avg
	clust_stats[,paste(pref, 'std', sep='')] <- stats[[i]]$std
	clust_stats[,paste(pref, 'skew', sep='')] <- stats[[i]]$skew
	clust_stats[,paste(pref, 'slope', sep='')] <- stats[[i]]$slope
	clust_stats[,paste(pref, 'slope_std', sep='')] <- stats[[i]]$slope_std
}

# The data frame is then saved as an csv file.
write.csv(clust_stats, file='data/cluster_stats.csv')

